version: '3.8'

volumes:
    postgres_data:
    static:

services:

    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        image: krankir/api_yamdb:latest
        restart: always
        volumes:
            - static:/static
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        image: nginx:1.21.3-alpine
        volumes:
            - static:/static
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - web
